### ISSUE TITLE
Double up?

### ISSUE THREAD

**Issue by Bandit** [rodneylab/sveltekit-seo#1]
https://github.com/rodneylab/sveltekit-seo/blob/c87d9b17dd0542e96dc3999bc29cd98721604221/src/lib/config/website.js#L16-L17

https://github.com/rodneylab/sveltekit-seo/blob/c87d9b17dd0542e96dc3999bc29cd98721604221/src/lib/config/website.js#L24-L25

**Comment by rodneylab** [comment]
Good spot! Removing both because the repo uses vite-imagetools to create responsive and SEO images now rather than imgix.  Thanks for pointing this out.

**Comment by rodneylab** [comment]
fixed now: [https://github.com/rodneylab/sveltekit-seo/commit/9714aab3b6b03b13a3d1e87fa28036126231a0d1](https://github.com/rodneylab/sveltekit-seo/commit/9714aab3b6b03b13a3d1e87fa28036126231a0d1)
